export const emptyForm = {
  company: '',
  job: '',
  link: '',
  salary: 0,
  date: '',
  workplace: 'select',
  description: '',
};

export const INPUT_FIELDS = {
  company: {
    label: 'Company:',
    type: 'text',
    prop: 'company',
    placeholder: 'Google, Amazon...',
    required: true,
    hasError: false,
    dataTest: 'company',
  },
  job: {
    label: 'Job:',
    type: 'text',
    prop: 'job',
    placeholder: 'Frontend Web Developer',
    required: true,
    dataTest: 'job',
    hasError: false,
  },
  jobLink: {
    label: "Job's link:",
    type: 'text',
    prop: 'link',
    placeholder: 'https://linkedin.com/google-job',
    dataTest: 'job-link',
    required: true,
    hasError: true,
  },
  salary: {
    label: 'Salary ($ / month):',
    type: 'number',
    prop: 'salary',
    placeholder: '',
    required: true,
    dataTest: 'salary',
    hasError: false,
  },
  date: {
    label: 'Date:',
    type: 'date',
    prop: 'date',
    placeholder: '',
    dataTest: 'date',
    required: true,
    hasError: false,
  },
  workplace: {
    label: 'Workplace:',
    type: 'select',
    prop: 'workplace',
    placeholder: '',
    required: true,
    dataTest: 'workplace',
    hasError: false,
  },
  description: {
    label: 'Description:',
    type: 'textarea',
    prop: 'description',
    required: false,
    placeholder: 'Web developer job with great salary...',
    dataTest: 'description',
    hasError: false,
  },
} as const;
